# -*- coding: utf-8 -*-
# 批次 1：北方针叶树、杨柳桦木类、常见落叶阔叶树补充（约 60 种）
# 目标类群：东北/华北/西北常见木本植物（避开已有 100 种）

P = "被子植物门"
DIC = "双子叶植物纲"
MONO = "单子叶植物纲"

PLANTS = [
# ---------- 裸子植物（针叶树）----------
{"name": "红皮云杉", "scientific_name": "Picea koraiensis",
 "path": {"kingdom": "植物界", "phylum": "裸子植物门", "class": "松杉纲", "order": "松杉目", "family": "松科", "genus": "云杉属"},
 "info": {"habit": "tree", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "evergreen", "growth_rate": "medium",
          "height_min_cm": 2000, "height_max_cm": 3000, "temperature_min_c": -100, "temperature_max_c": -100,
          "description": "常绿乔木，树冠尖塔形，小枝有木钉状叶枕；东北林区主要用材树种。"}},
{"name": "白扦", "scientific_name": "Picea meyeri",
 "path": {"kingdom": "植物界", "phylum": "裸子植物门", "class": "松杉纲", "order": "松杉目", "family": "松科", "genus": "云杉属"},
 "info": {"habit": "tree", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 1500, "height_max_cm": 2500, "description": "常绿乔木，华北山地常见，耐寒耐旱。"}},
{"name": "青扦", "scientific_name": "Picea wilsonii",
 "path": {"kingdom": "植物界", "phylum": "裸子植物门", "class": "松杉纲", "order": "松杉目", "family": "松科", "genus": "云杉属"},
 "info": {"habit": "tree", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 1500, "height_max_cm": 2800, "description": "常绿乔木，产华北高山，树形优美。"}},
{"name": "兴安落叶松", "scientific_name": "Larix gmelinii",
 "path": {"kingdom": "植物界", "phylum": "裸子植物门", "class": "松杉纲", "order": "松杉目", "family": "松科", "genus": "落叶松属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 2000, "height_max_cm": 3500, "temperature_min_c": -100, "temperature_max_c": -100,
          "description": "落叶乔木，大兴安岭主要树种，极耐寒。"}},
{"name": "华北落叶松", "scientific_name": "Larix principis-rupprechtii",
 "path": {"kingdom": "植物界", "phylum": "裸子植物门", "class": "松杉纲", "order": "松杉目", "family": "松科", "genus": "落叶松属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1500, "height_max_cm": 3000, "description": "落叶乔木，华北高山造林树种。"}},
{"name": "长白落叶松", "scientific_name": "Larix olgensis",
 "path": {"kingdom": "植物界", "phylum": "裸子植物门", "class": "松杉纲", "order": "松杉目", "family": "松科", "genus": "落叶松属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 2000, "height_max_cm": 3000, "description": "落叶乔木，长白山及东北东部主要树种。"}},
{"name": "樟子松", "scientific_name": "Pinus sylvestris var. mongolica",
 "path": {"kingdom": "植物界", "phylum": "裸子植物门", "class": "松杉纲", "order": "松杉目", "family": "松科", "genus": "松属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 1500, "height_max_cm": 3000, "description": "常绿乔木，大兴安岭及沙地造林先锋树种，极耐旱。"}},
{"name": "红松", "scientific_name": "Pinus koraiensis",
 "path": {"kingdom": "植物界", "phylum": "裸子植物门", "class": "松杉纲", "order": "松杉目", "family": "松科", "genus": "松属"},
 "info": {"habit": "tree", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "evergreen", "growth_rate": "slow",
          "height_min_cm": 2000, "height_max_cm": 4000, "description": "常绿乔木，东北红松阔叶林优势种，种子为松子。"}},
{"name": "云杉", "scientific_name": "Picea asperata",
 "path": {"kingdom": "植物界", "phylum": "裸子植物门", "class": "松杉纲", "order": "松杉目", "family": "松科", "genus": "云杉属"},
 "info": {"habit": "tree", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 2000, "height_max_cm": 4500, "description": "常绿乔木，产我国西部及华北高山。"}},
{"name": "杜松", "scientific_name": "Juniperus rigida",
 "path": {"kingdom": "植物界", "phylum": "裸子植物门", "class": "松杉纲", "order": "松杉目", "family": "柏科", "genus": "刺柏属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 500, "height_max_cm": 1200, "description": "常绿乔木或灌木，针叶三棱，华北及东北阳坡常见。"}},
{"name": "侧柏变种-千头柏", "scientific_name": "Platycladus orientalis 'Sieboldii'",
 "path": {"kingdom": "植物界", "phylum": "裸子植物门", "class": "松杉纲", "order": "松杉目", "family": "柏科", "genus": "侧柏属"},
 "rank": "cultivar",
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 200, "height_max_cm": 500, "description": "侧柏栽培品种，树冠卵圆形，华北常见绿篱。"}},
{"name": "冷杉", "scientific_name": "Abies nephrolepis",
 "path": {"kingdom": "植物界", "phylum": "裸子植物门", "class": "松杉纲", "order": "松杉目", "family": "松科", "genus": "冷杉属"},
 "info": {"habit": "tree", "light": "half_shade", "water": "moist", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 2000, "height_max_cm": 3000, "description": "常绿乔木，东北东部山地耐阴树种。"}},

# ---------- 杨柳科补充 ----------
{"name": "青杨", "scientific_name": "Populus cathayana",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "杨柳目", "family": "杨柳科", "genus": "杨属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous", "growth_rate": "fast",
          "height_min_cm": 1500, "height_max_cm": 3000, "description": "落叶乔木，华北山地河岸常见。"}},
{"name": "小叶杨", "scientific_name": "Populus simonii",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "杨柳目", "family": "杨柳科", "genus": "杨属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous", "growth_rate": "fast",
          "height_min_cm": 1000, "height_max_cm": 2000, "description": "落叶乔木，耐旱耐寒，西北防护林树种。"}},
{"name": "箭杆杨", "scientific_name": "Populus nigra var. thevestina",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "杨柳目", "family": "杨柳科", "genus": "杨属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1500, "height_max_cm": 3000, "description": "落叶乔木，树冠窄圆柱形，华北行道树。"}},
{"name": "钻天杨", "scientific_name": "Populus nigra var. italica",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "杨柳目", "family": "杨柳科", "genus": "杨属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1500, "height_max_cm": 3000, "description": "落叶乔木，树冠圆柱形，北方常见行道树。"}},
{"name": "五蕊柳", "scientific_name": "Salix pentandra",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "杨柳目", "family": "杨柳科", "genus": "柳属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 800, "height_max_cm": 1500, "description": "落叶乔木，东北河边湿地常见。"}},
{"name": "粉枝柳", "scientific_name": "Salix rorida",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "杨柳目", "family": "杨柳科", "genus": "柳属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 600, "height_max_cm": 1500, "description": "落叶乔木或灌木，东北水边常见。"}},
{"name": "筐柳", "scientific_name": "Salix linearistipularis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "杨柳目", "family": "杨柳科", "genus": "柳属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 200, "height_max_cm": 400, "description": "灌木，耐水湿，华北河岸固堤植物。"}},
{"name": "细叶沼柳", "scientific_name": "Salix rosmarinifolia",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "杨柳目", "family": "杨柳科", "genus": "柳属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 200, "description": "匍匐灌木，东北沼泽湿地常见。"}},

# ---------- 桦木科 ----------
{"name": "白桦", "scientific_name": "Betula platyphylla",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "壳斗目", "family": "桦木科", "genus": "桦木属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous", "growth_rate": "fast",
          "height_min_cm": 1500, "height_max_cm": 2500, "bloom_months": [5], "description": "落叶乔木，树皮白色，东北华北山地先锋树种。"}},
{"name": "黑桦", "scientific_name": "Betula dahurica",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "壳斗目", "family": "桦木科", "genus": "桦木属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1000, "height_max_cm": 2000, "description": "落叶乔木，树皮黑褐色，东北山地阳坡常见。"}},
{"name": "硕桦", "scientific_name": "Betula costata",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "壳斗目", "family": "桦木科", "genus": "桦木属"},
 "info": {"habit": "tree", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1500, "height_max_cm": 3000, "description": "落叶乔木，木材坚硬，东北用材树种。"}},
{"name": "毛榛", "scientific_name": "Corylus mandshurica",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "壳斗目", "family": "桦木科", "genus": "榛属"},
 "info": {"habit": "shrub", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 200, "height_max_cm": 500, "description": "灌木，坚果可食，东北华北山地林下常见。"}},
{"name": "榛", "scientific_name": "Corylus heterophylla",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "壳斗目", "family": "桦木科", "genus": "榛属"},
 "info": {"habit": "shrub", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 400, "bloom_months": [4, 5], "description": "灌木，坚果（榛子）著名干果，北方荒山灌丛优势种。"}},
{"name": "鹅耳枥", "scientific_name": "Carpinus turczaninowii",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "壳斗目", "family": "桦木科", "genus": "鹅耳枥属"},
 "info": {"habit": "tree", "light": "half_shade", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 800, "height_max_cm": 1500, "description": "落叶乔木，耐阴，华北山地常见。"}},
{"name": "千金榆", "scientific_name": "Carpinus cordata",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "壳斗目", "family": "桦木科", "genus": "鹅耳枥属"},
 "info": {"habit": "tree", "light": "half_shade", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1000, "height_max_cm": 1800, "description": "落叶乔木，东北华北山地林下常见。"}},
{"name": "辽东桤木", "scientific_name": "Alnus hirsuta",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "壳斗目", "family": "桦木科", "genus": "桤木属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1000, "height_max_cm": 2000, "description": "落叶乔木，耐水湿，东北河岸常见。"}},

# ---------- 壳斗科/山毛榉补充 ----------
{"name": "蒙古栎", "scientific_name": "Quercus mongolica",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "壳斗目", "family": "壳斗科", "genus": "栎属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1500, "height_max_cm": 3000, "description": "落叶乔木，东北华北山地阔叶林主要建群种，耐旱耐寒。"}},
{"name": "辽东栎", "scientific_name": "Quercus liaotungensis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "壳斗目", "family": "壳斗科", "genus": "栎属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1000, "height_max_cm": 2000, "description": "落叶乔木，华北山地阳坡优势种。"}},
{"name": "槲栎", "scientific_name": "Quercus aliena",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "壳斗目", "family": "壳斗科", "genus": "栎属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1500, "height_max_cm": 2500, "description": "落叶乔木，华北至华中常见。"}},
{"name": "槲树", "scientific_name": "Quercus dentata",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "壳斗目", "family": "壳斗科", "genus": "栎属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1000, "height_max_cm": 2500, "description": "落叶乔木，叶大，华北山地常见。"}},
{"name": "板栗", "scientific_name": "Castanea mollissima",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "壳斗目", "family": "壳斗科", "genus": "栗属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1000, "height_max_cm": 2000, "bloom_months": [5, 6], "description": "落叶乔木，坚果著名干果，华北山区广泛栽培。"}},

# ---------- 榆科补充 ----------
{"name": "裂叶榆", "scientific_name": "Ulmus laciniata",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "荨麻目", "family": "榆科", "genus": "榆属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1000, "height_max_cm": 2000, "description": "落叶乔木，东北华北山地林区常见。"}},
{"name": "大果榆", "scientific_name": "Ulmus macrocarpa",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "荨麻目", "family": "榆科", "genus": "榆属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 800, "height_max_cm": 1500, "description": "落叶乔木，耐旱，华北干旱山地常见。"}},
{"name": "春榆", "scientific_name": "Ulmus davidiana var. japonica",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "荨麻目", "family": "榆科", "genus": "榆属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1000, "height_max_cm": 2500, "description": "落叶乔木，东北华北常见用材树种。"}},
{"name": "青檀", "scientific_name": "Pteroceltis tatarinowii",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "荨麻目", "family": "榆科", "genus": "青檀属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1000, "height_max_cm": 2000, "description": "落叶乔木，我国特有，树皮为宣纸原料。"}},
{"name": "黑弹树", "scientific_name": "Celtis bungeana",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "荨麻目", "family": "榆科", "genus": "朴属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 800, "height_max_cm": 1500, "description": "落叶乔木，华北常见，果熟紫黑色。"}},
{"name": "小叶朴", "scientific_name": "Celtis koraiensis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "荨麻目", "family": "榆科", "genus": "朴属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1000, "height_max_cm": 2000, "description": "落叶乔木，东北华北山地常见。"}},

# ---------- 桑科/荨麻科补充 ----------
{"name": "葎草", "scientific_name": "Humulus scandens",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "荨麻目", "family": "桑科", "genus": "葎草属"},
 "info": {"habit": "vine", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 500, "description": "一年生缠绕草本，荒地常见杂草。"}},
{"name": "大麻", "scientific_name": "Cannabis sativa",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "荨麻目", "family": "桑科", "genus": "大麻属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 300, "description": "一年生草本，纤维植物，栽培历史久。"}},
{"name": "苎麻", "scientific_name": "Boehmeria nivea",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "荨麻目", "family": "荨麻科", "genus": "苎麻属"},
 "info": {"habit": "shrub", "light": "half_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 200, "description": "半灌木，茎皮纤维重要纺织原料。"}},
{"name": "宽叶荨麻", "scientific_name": "Urtica laetevirens",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "荨麻目", "family": "荨麻科", "genus": "荨麻属"},
 "info": {"habit": "herb", "light": "half_shade", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 150, "description": "多年生草本，茎有刺毛，林下湿地常见。"}},
]
