# -*- coding: utf-8 -*-
# 批次 6：更多北方常见植物补齐（约 45 种）——观花、野菜、杂草、果树、药用

P = "被子植物门"
DIC = "双子叶植物纲"
MONO = "单子叶植物纲"

PLANTS = [
# ---------- 蔷薇科观赏补充 ----------
{"name": "贴梗海棠-倭海棠", "scientific_name": "Chaenomeles japonica",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "木瓜属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 150, "bloom_months": [4, 5], "description": "落叶灌木，矮生海棠，北方园林。"}},
{"name": "垂丝海棠", "scientific_name": "Malus halliana",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "苹果属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 300, "height_max_cm": 800, "bloom_months": [4, 5], "description": "落叶小乔木，花梗下垂，观赏海棠。"}},
{"name": "紫叶矮樱", "scientific_name": "Prunus × cistena",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "李属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 250, "bloom_months": [4, 5], "description": "落叶灌木，紫叶观赏，北方园林色块。"}},
{"name": "红瑞木", "scientific_name": "Cornus alba",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "山茱萸目", "family": "山茱萸科", "genus": "山茱萸属"},
 "info": {"habit": "shrub", "light": "half_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 150, "height_max_cm": 300, "bloom_months": [5, 6], "description": "落叶灌木，秋冬枝干鲜红，北方园林。"}},
{"name": "迎红杜鹃", "scientific_name": "Rhododendron mucronulatum",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "杜鹃花目", "family": "杜鹃花科", "genus": "杜鹃花属"},
 "info": {"habit": "shrub", "light": "half_shade", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 300, "bloom_months": [4, 5], "description": "落叶灌木，早春粉花，东北华北山地（金达莱）。"}},
{"name": "大字杜鹃", "scientific_name": "Rhododendron schlippenbachii",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "杜鹃花目", "family": "杜鹃花科", "genus": "杜鹃花属"},
 "info": {"habit": "shrub", "light": "half_shade", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 300, "bloom_months": [5, 6], "description": "落叶灌木，辽宁山地杜鹃。"}},

# ---------- 野菜/山野菜补充 ----------
{"name": "蕨菜", "scientific_name": "Pteridium aquilinum var. latiusculum",
 "path": {"kingdom": "植物界", "phylum": "蕨类植物门", "class": "蕨纲", "order": "蕨目", "family": "蕨科", "genus": "蕨属"},
 "info": {"habit": "herb", "light": "half_shade", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 120, "description": "多年生蕨类，嫩芽（蕨菜）著名山野菜。"}},
{"name": "荠菜-北方", "scientific_name": "Capsella bursa-pastoris",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "十字花目", "family": "十字花科", "genus": "荠属"},
 "rank": "subspecies",
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 50, "description": "早春野菜。"}},
{"name": "苣荬菜", "scientific_name": "Sonchus arvensis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "苦苣菜属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "bloom_months": [6, 7, 8], "description": "多年生草本，苦菜，北方田间野菜。"}},
{"name": "苦苣菜", "scientific_name": "Sonchus oleraceus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "苦苣菜属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "bloom_months": [5, 6, 7], "description": "一年生草本，野菜。"}},
{"name": "马齿苋", "scientific_name": "Portulaca oleracea",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "马齿苋科", "genus": "马齿苋属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 10, "height_max_cm": 30, "bloom_months": [6, 7, 8], "description": "一年生肉质草本，野菜与中药。"}},
{"name": "灰灰菜", "scientific_name": "Chenopodium album",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "苋科", "genus": "藜属"},
 "rank": "subspecies",
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "description": "藜的俗称，春夏季野菜。"}},
{"name": "曲麻菜", "scientific_name": "Sonchus wightianus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "苦苣菜属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 40, "height_max_cm": 120, "bloom_months": [6, 7, 8], "description": "多年生草本，北方常见苦菜。"}},

# ---------- 果树补充 ----------
{"name": "山葡萄-北冰红", "scientific_name": "Vitis amurensis cv.",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "鼠李目", "family": "葡萄科", "genus": "葡萄属"},
 "rank": "cultivar",
 "info": {"habit": "vine", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 300, "height_max_cm": 1000, "description": "山葡萄酿酒品种，东北冰酒原料。"}},
{"name": "树莓", "scientific_name": "Rubus idaeus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "悬钩子属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 200, "bloom_months": [5, 6], "description": "落叶灌木，浆果（覆盆子）可食。"}},
{"name": "蓝莓", "scientific_name": "Vaccinium uliginosum",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "杜鹃花目", "family": "杜鹃花科", "genus": "越橘属"},
 "info": {"habit": "shrub", "light": "half_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 200, "bloom_months": [5, 6], "description": "落叶灌木（笃斯越橘），酸性土壤，蓝紫色浆果，东北山地。"}},
{"name": "红豆越橘", "scientific_name": "Vaccinium vitis-idaea",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "杜鹃花目", "family": "杜鹃花科", "genus": "越橘属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 10, "height_max_cm": 30, "bloom_months": [6, 7], "description": "常绿矮小灌木，红浆果，大兴安岭。"}},
{"name": "沙地柏", "scientific_name": "Juniperus sabina",
 "path": {"kingdom": "植物界", "phylum": "裸子植物门", "class": "松杉纲", "order": "松杉目", "family": "柏科", "genus": "圆柏属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 50, "height_max_cm": 200, "description": "匍匐常绿灌木，沙地固沙与地被。"}},

# ---------- 杂类补充 ----------
{"name": "二月兰", "scientific_name": "Orychophragmus violaceus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "十字花目", "family": "十字花科", "genus": "诸葛菜属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moderate", "life_cycle": "biennial", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 50, "bloom_months": [3, 4, 5], "description": "二年生草本，早春蓝紫花，北方林缘荒地。"}},
{"name": "二月蓝-变种", "scientific_name": "Orychophragmus violaceus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "十字花目", "family": "十字花科", "genus": "诸葛菜属"},
 "rank": "variety",
 "info": {"habit": "herb", "light": "half_sun", "water": "moderate", "life_cycle": "biennial", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 50, "bloom_months": [3, 4], "description": "二月兰白花变型。"}},

{"name": "金鱼草", "scientific_name": "Antirrhinum majus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "车前科", "genus": "金鱼草属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 80, "bloom_months": [6, 7, 8], "description": "多年生常作一年生，花坛花卉。"}},
{"name": "矮牵牛", "scientific_name": "Petunia hybrida",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "茄目", "family": "茄科", "genus": "碧冬茄属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 60, "bloom_months": [6, 7, 8, 9], "description": "一年生草本，花大色艳，盆花与花坛。"}},
{"name": "一串蓝", "scientific_name": "Salvia farinacea",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "唇形科", "genus": "鼠尾草属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 40, "height_max_cm": 80, "bloom_months": [6, 7, 8, 9], "description": "一年生草本，蓝花，花坛。"}},
{"name": "彩叶草", "scientific_name": "Coleus scutellarioides",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "唇形科", "genus": "鞘蕊花属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 80, "description": "多年生草本，叶色斑斓，观叶植物。"}},

# ---------- 更多蔷薇/桃李属果树/观赏 ----------
{"name": "碧桃", "scientific_name": "Prunus persica f. duplex",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "桃属"},
 "rank": "form",
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 300, "height_max_cm": 800, "bloom_months": [4], "description": "桃的观赏品种，重瓣红花，北方春景。"}},
{"name": "紫叶桃", "scientific_name": "Prunus persica f. atropurpurea",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "桃属"},
 "rank": "form",
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 300, "height_max_cm": 600, "bloom_months": [4], "description": "紫叶观赏桃。"}},
{"name": "山毛桃", "scientific_name": "Prunus davidiana",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "桃属"},
 "rank": "variety",
 "info": {"habit": "tree", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 400, "height_max_cm": 800, "bloom_months": [3, 4], "description": "山桃变种。"}},

# 忍冬科补充
{"name": "六道木", "scientific_name": "Abelia biflora",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "川续断目", "family": "忍冬科", "genus": "六道木属"},
 "info": {"habit": "shrub", "light": "half_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 300, "bloom_months": [6, 7], "description": "落叶灌木，华北山地灌丛。"}},
{"name": "猬实", "scientific_name": "Kolkwitzia amabilis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "川续断目", "family": "忍冬科", "genus": "猬实属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 300, "bloom_months": [5, 6], "description": "落叶灌木，我国特有，果密被刺毛如猬。"}},

# 灌木-山茱萸/五加
{"name": "刺五加", "scientific_name": "Eleutherococcus senticosus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "伞形目", "family": "五加科", "genus": "五加属"},
 "info": {"habit": "shrub", "light": "half_shade", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 300, "bloom_months": [6, 7], "description": "落叶灌木，茎有刺，根皮药用，东北林区。"}},
{"name": "辽东楤木", "scientific_name": "Aralia elata",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "伞形目", "family": "五加科", "genus": "楤木属"},
 "info": {"habit": "shrub", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 200, "height_max_cm": 600, "bloom_months": [8, 9], "description": "落叶小乔木，嫩芽（刺嫩芽）名贵山野菜。"}},

# 苔草/莎草
{"name": "苔草", "scientific_name": "Carex tristachya",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "禾本目", "family": "莎草科", "genus": "苔草属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 80, "description": "多年生草本，林下湿地成片。"}},
{"name": "乌拉草", "scientific_name": "Carex meyeriana",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "禾本目", "family": "莎草科", "genus": "苔草属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 60, "description": "多年生草本，东北沼泽（塔头），旧时絮鞋。"}},

# 天南星补充
{"name": "菖蒲", "scientific_name": "Acorus calamus",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "天南星目", "family": "天南星科", "genus": "菖蒲属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "aquatic", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 60, "height_max_cm": 120, "bloom_months": [5, 6], "description": "多年生水生草本，端午习俗植物。"}},
{"name": "独角莲", "scientific_name": "Typhonium giganteum",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "天南星目", "family": "天南星科", "genus": "犁头尖属"},
 "info": {"habit": "herb", "light": "half_shade", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 80, "bloom_months": [6, 7], "description": "多年生草本，块茎药用。"}},

# 睡莲科补充
{"name": "睡莲", "scientific_name": "Nymphaea tetragona",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "睡莲目", "family": "睡莲科", "genus": "睡莲属"},
 "info": {"habit": "aquatic", "light": "full_sun", "water": "aquatic", "life_cycle": "perennial", "foliage": "deciduous",
          "bloom_months": [6, 7, 8], "description": "多年生水生草本，观赏荷花池配植。"}},

# 罂粟/其他
{"name": "大花金鸡菊", "scientific_name": "Coreopsis grandiflora",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "金鸡菊属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 80, "bloom_months": [6, 7, 8], "description": "多年生草本，黄花花海，北方路旁逸生。"}},
{"name": "黑心金光菊", "scientific_name": "Rudbeckia hirta",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "金光菊属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "bloom_months": [6, 7, 8, 9], "description": "一年生或多年生，金黄色花。"}},
]
