# -*- coding: utf-8 -*-
# 批次 3：菊科、唇形科、玄参科等北方常见草本（约 70 种）

P = "被子植物门"
DIC = "双子叶植物纲"

PLANTS = [
# ---------- 菊科（菊目）----------
{"name": "向日葵", "scientific_name": "Helianthus annuus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "向日葵属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous", "growth_rate": "fast",
          "height_min_cm": 100, "height_max_cm": 300, "bloom_months": [7, 8, 9], "description": "一年生高大草本，油料与观赏作物，北方广泛栽培。"}},
{"name": "菊花", "scientific_name": "Chrysanthemum morifolium",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "菊属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 60, "height_max_cm": 150, "bloom_months": [9, 10, 11], "description": "多年生草本，著名观赏花卉与茶饮，品种繁多。"}},
{"name": "野菊", "scientific_name": "Chrysanthemum indicum",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "菊属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "bloom_months": [9, 10], "description": "多年生草本，黄花，北方山坡路边常见。"}},
{"name": "蒲公英", "scientific_name": "Taraxacum mongolicum",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "蒲公英属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 10, "height_max_cm": 30, "bloom_months": [4, 5, 6], "description": "多年生草本，黄花，药用与野菜，北方各地常见。"}},
{"name": "刺儿菜", "scientific_name": "Cirsium setosum",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "蓟属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "bloom_months": [5, 6, 7], "description": "多年生草本，叶缘有刺，田间荒地常见杂草。"}},
{"name": "大蓟", "scientific_name": "Cirsium japonicum",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "蓟属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 150, "bloom_months": [6, 7, 8], "description": "多年生草本，药用植物。"}},
{"name": "艾", "scientific_name": "Artemisia argyi",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "蒿属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 150, "bloom_months": [8, 9], "description": "多年生草本，端午节习俗用叶，艾灸原料。"}},
{"name": "茵陈蒿", "scientific_name": "Artemisia capillaris",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "蒿属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "bloom_months": [8, 9], "description": "半灌木状草本，幼苗药用（茵陈）。"}},
{"name": "黄花蒿", "scientific_name": "Artemisia annua",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "蒿属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 200, "bloom_months": [8, 9, 10], "description": "一年生草本，提取青蒿素，药用植物。"}},
{"name": "紫菀", "scientific_name": "Aster tataricus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "紫菀属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 150, "bloom_months": [8, 9, 10], "description": "多年生草本，根药用，北方林下湿地。"}},
{"name": "飞蓬", "scientific_name": "Erigeron acris",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "飞蓬属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "biennial", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 60, "bloom_months": [7, 8], "description": "二年生草本，北方山坡草地常见。"}},
{"name": "一年蓬", "scientific_name": "Erigeron annuus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "飞蓬属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "bloom_months": [6, 7, 8], "description": "一年生草本，入侵杂草，路旁荒地常见。"}},
{"name": "狗娃花", "scientific_name": "Heteropappus hispidus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "狗娃花属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 80, "bloom_months": [7, 8, 9], "description": "多年生草本，北方旱地常见。"}},
{"name": "苍术", "scientific_name": "Atractylodes lancea",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "苍术属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "bloom_months": [7, 8], "description": "多年生草本，根茎著名中药，北方山地。"}},
{"name": "白术", "scientific_name": "Atractylodes macrocephala",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "苍术属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 80, "bloom_months": [8, 9], "description": "多年生草本，根茎药材。"}},
{"name": "牛蒡", "scientific_name": "Arctium lappa",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "牛蒡属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "biennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 200, "bloom_months": [7, 8], "description": "二年生草本，根与果实药用，北方路边常见。"}},
{"name": "苍耳", "scientific_name": "Xanthium sibiricum",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "苍耳属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 120, "bloom_months": [7, 8], "description": "一年生草本，带钩刺果实沾衣，荒地常见。"}},
{"name": "旋覆花", "scientific_name": "Inula japonica",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "旋覆花属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "bloom_months": [6, 7, 8], "description": "多年生草本，黄花，湿地河岸常见。"}},
{"name": "大丽花", "scientific_name": "Dahlia pinnata",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "大丽花属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 200, "bloom_months": [7, 8, 9], "description": "多年生草本（块根），栽培观赏花卉。"}},
{"name": "波斯菊", "scientific_name": "Cosmos bipinnatus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "秋英属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 150, "bloom_months": [7, 8, 9, 10], "description": "一年生草本，花色丰富，北方常见观赏花卉。"}},
{"name": "百日菊", "scientific_name": "Zinnia elegans",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "百日菊属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "bloom_months": [7, 8, 9], "description": "一年生草本，观赏花卉。"}},
{"name": "万寿菊", "scientific_name": "Tagetes erecta",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "万寿菊属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 120, "bloom_months": [7, 8, 9, 10], "description": "一年生草本，黄橙色花，花坛常见。"}},
{"name": "翠菊", "scientific_name": "Callistephus chinensis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "菊目", "family": "菊科", "genus": "翠菊属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "bloom_months": [7, 8, 9], "description": "一年生草本，国产著名观赏花卉。"}},

# ---------- 唇形科补充 ----------
{"name": "丹参", "scientific_name": "Salvia miltiorrhiza",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "唇形科", "genus": "鼠尾草属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 40, "height_max_cm": 80, "bloom_months": [5, 6, 7], "description": "多年生草本，根药用，华北山地栽培。"}},
{"name": "黄芩", "scientific_name": "Scutellaria baicalensis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "唇形科", "genus": "黄芩属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 60, "bloom_months": [7, 8], "description": "多年生草本，根著名中药，北方山地阳坡。"}},
{"name": "益母草", "scientific_name": "Leonurus japonicus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "唇形科", "genus": "益母草属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 120, "bloom_months": [6, 7, 8], "description": "一年生或二年生草本，妇科要药，路边荒地常见。"}},
{"name": "夏枯草", "scientific_name": "Prunella vulgaris",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "唇形科", "genus": "夏枯草属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 50, "bloom_months": [5, 6], "description": "多年生草本，果穗药用，北方山坡草地。"}},
{"name": "荆芥", "scientific_name": "Nepeta cataria",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "唇形科", "genus": "荆芥属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 40, "height_max_cm": 100, "bloom_months": [6, 7, 8], "description": "多年生草本，芳香，药用与调料。"}},
{"name": "裂叶荆芥", "scientific_name": "Schizonepeta tenuifolia",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "唇形科", "genus": "裂叶荆芥属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 80, "bloom_months": [6, 7], "description": "一年生草本，解表中药。"}},
{"name": "香薷", "scientific_name": "Elsholtzia ciliata",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "唇形科", "genus": "香薷属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 80, "bloom_months": [7, 8, 9], "description": "一年生草本，芳香，北方田野常见。"}},
{"name": "活血丹", "scientific_name": "Glechoma longituba",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "唇形科", "genus": "活血丹属"},
 "info": {"habit": "herb", "light": "half_shade", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 10, "height_max_cm": 30, "bloom_months": [4, 5], "description": "多年生匍匐草本，药用，林下湿地。"}},
{"name": "藿香", "scientific_name": "Agastache rugosa",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "唇形科", "genus": "藿香属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 150, "bloom_months": [7, 8, 9], "description": "多年生草本，芳香化湿中药，北方常见栽培。"}},
{"name": "一串红", "scientific_name": "Salvia splendens",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "唇形科", "genus": "鼠尾草属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 40, "height_max_cm": 100, "bloom_months": [7, 8, 9, 10], "description": "多年生常作一年生栽培，红花串串，花坛常见。"}},

# ---------- 玄参科/车前科补充 ----------
{"name": "毛地黄", "scientific_name": "Digitalis purpurea",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "车前科", "genus": "毛地黄属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moderate", "life_cycle": "biennial", "foliage": "deciduous",
          "height_min_cm": 60, "height_max_cm": 120, "bloom_months": [6, 7], "description": "二年生草本，花冠钟形，强心苷药用植物。"}},
{"name": "车前", "scientific_name": "Plantago asiatica",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "车前科", "genus": "车前属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 10, "height_max_cm": 40, "bloom_months": [5, 6, 7], "description": "多年生草本，种子与全草药用，路旁常见。"}},
{"name": "平车前", "scientific_name": "Plantago depressa",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "车前科", "genus": "车前属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 10, "height_max_cm": 30, "bloom_months": [5, 6, 7], "description": "一年生草本，北方旱地路边常见。"}},
# ---------- 毛茛科 ----------
{"name": "白头翁", "scientific_name": "Pulsatilla chinensis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "毛茛目", "family": "毛茛科", "genus": "白头翁属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 10, "height_max_cm": 30, "bloom_months": [4, 5], "description": "多年生草本，根药用，果期宿存花柱如白发。"}},
{"name": "毛茛", "scientific_name": "Ranunculus japonicus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "毛茛目", "family": "毛茛科", "genus": "毛茛属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 70, "bloom_months": [5, 6], "description": "多年生草本，黄花，有毒，水边湿地常见。"}},
{"name": "石龙芮", "scientific_name": "Ranunculus sceleratus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "毛茛目", "family": "毛茛科", "genus": "毛茛属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "aquatic", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 60, "bloom_months": [4, 5], "description": "一年生草本，生于水湿处。"}},
{"name": "乌头", "scientific_name": "Aconitum carmichaelii",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "毛茛目", "family": "毛茛科", "genus": "乌头属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 60, "height_max_cm": 150, "bloom_months": [8, 9], "description": "多年生草本，剧毒，块根为重要中药。"}},
{"name": "草乌", "scientific_name": "Aconitum kusnezoffii",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "毛茛目", "family": "毛茛科", "genus": "乌头属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 60, "height_max_cm": 150, "bloom_months": [8, 9], "description": "多年生草本，剧毒药用植物，东北山地。"}},
{"name": "大花飞燕草", "scientific_name": "Delphinium grandiflorum",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "毛茛目", "family": "毛茛科", "genus": "翠雀属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "bloom_months": [7, 8], "description": "多年生草本，蓝紫色花，北方山地草原。"}},
{"name": "唐松草", "scientific_name": "Thalictrum aquilegifolium var. sibiricum",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "毛茛目", "family": "毛茛科", "genus": "唐松草属"},
 "info": {"habit": "herb", "light": "half_shade", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 150, "bloom_months": [6, 7], "description": "多年生草本，林下阴湿处。"}},
{"name": "升麻", "scientific_name": "Cimicifuga foetida",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "毛茛目", "family": "毛茛科", "genus": "升麻属"},
 "info": {"habit": "herb", "light": "half_shade", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 200, "bloom_months": [7, 8], "description": "多年生草本，根茎中药，北方林下。"}},

# ---------- 十字花科补充 ----------
{"name": "油菜", "scientific_name": "Brassica rapa subsp. oleifera",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "十字花目", "family": "十字花科", "genus": "芸薹属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "biennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 150, "bloom_months": [4, 5], "description": "油料蔬菜作物，北方春油菜花田。"}},
{"name": "独行菜", "scientific_name": "Lepidium apetalum",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "十字花目", "family": "十字花科", "genus": "独行菜属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 10, "height_max_cm": 30, "bloom_months": [5, 6], "description": "一年生草本，种子（葶苈子）药用，北方旱地常见。"}},
{"name": "菥蓂", "scientific_name": "Thlaspi arvense",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "十字花目", "family": "十字花科", "genus": "遏蓝菜属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 60, "bloom_months": [5, 6], "description": "一年生草本，麦田常见杂草。"}},
{"name": "蔊菜", "scientific_name": "Rorippa indica",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "十字花目", "family": "十字花科", "genus": "蔊菜属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moist", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 50, "bloom_months": [4, 5], "description": "一年生草本，水田沟边常见野菜。"}},

# ---------- 蓼科 / 苋科补充 ----------
{"name": "红蓼", "scientific_name": "Polygonum orientale",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "蓼科", "genus": "蓼属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moist", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 300, "bloom_months": [6, 7, 8], "description": "一年生草本，水边湿地常见红穗。"}},
{"name": "水蓼", "scientific_name": "Polygonum hydropiper",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "蓼科", "genus": "蓼属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moist", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 40, "height_max_cm": 100, "bloom_months": [6, 7, 8], "description": "一年生草本，辛辣味，水湿处常见。"}},
{"name": "酸模叶蓼", "scientific_name": "Polygonum lapathifolium",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "蓼科", "genus": "蓼属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moist", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 120, "bloom_months": [6, 7, 8], "description": "一年生草本，田间沟边常见。"}},
{"name": "巴天酸模", "scientific_name": "Rumex patientia",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "蓼科", "genus": "酸模属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 60, "height_max_cm": 150, "bloom_months": [6, 7], "description": "多年生草本，河边路旁常见。"}},
{"name": "扁蓄", "scientific_name": "Polygonum aviculare",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "蓼科", "genus": "蓼属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 10, "height_max_cm": 50, "bloom_months": [6, 7, 8], "description": "一年生草本，路边荒地常见，药用。"}},
{"name": "藜", "scientific_name": "Chenopodium album",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "苋科", "genus": "藜属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 200, "bloom_months": [6, 7, 8], "description": "一年生草本（灰菜），常见野菜与杂草。"}},
{"name": "小藜", "scientific_name": "Chenopodium serotinum",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "苋科", "genus": "藜属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 80, "bloom_months": [6, 7], "description": "一年生草本，农田常见杂草。"}},
{"name": "苋菜", "scientific_name": "Amaranthus tricolor",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "苋科", "genus": "苋属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "bloom_months": [7, 8], "description": "一年生草本，叶菜。"}},
{"name": "反枝苋", "scientific_name": "Amaranthus retroflexus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "苋科", "genus": "苋属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "bloom_months": [7, 8], "description": "一年生草本，旱地田间常见杂草。"}},
]
