# -*- coding: utf-8 -*-
# 批次 4：伞形科/茄科/葫芦科蔬菜、百合科/鸢尾科花卉、禾本科等（约 65 种）

P = "被子植物门"
DIC = "双子叶植物纲"
MONO = "单子叶植物纲"

PLANTS = [
# ---------- 伞形科（伞形目）----------
{"name": "胡萝卜", "scientific_name": "Daucus carota var. sativa",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "伞形目", "family": "伞形科", "genus": "胡萝卜属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "biennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "description": "二年生蔬菜，直根食用，北方广泛栽培。"}},
{"name": "芹菜", "scientific_name": "Apium graveolens",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "伞形目", "family": "伞形科", "genus": "芹属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moist", "life_cycle": "biennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 100, "description": "二年生蔬菜，叶柄食用。"}},
{"name": "香菜", "scientific_name": "Coriandrum sativum",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "伞形目", "family": "伞形科", "genus": "芫荽属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 60, "description": "一年生蔬菜，全株作调味。"}},
{"name": "小茴香", "scientific_name": "Foeniculum vulgare",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "伞形目", "family": "伞形科", "genus": "茴香属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 200, "description": "多年生草本，茎叶作蔬菜与香料。"}},
{"name": "防风", "scientific_name": "Saposhnikovia divaricata",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "伞形目", "family": "伞形科", "genus": "防风属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 100, "description": "多年生草本，根著名中药，北方草原山地。"}},
{"name": "当归", "scientific_name": "Angelica sinensis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "伞形目", "family": "伞形科", "genus": "当归属"},
 "info": {"habit": "herb", "light": "half_shade", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 200, "description": "多年生草本，根为补血要药，北方高山栽培。"}},
{"name": "白芷", "scientific_name": "Angelica dahurica",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "伞形目", "family": "伞形科", "genus": "当归属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 200, "description": "多年生草本，根药用，北方栽培。"}},
{"name": "柴胡", "scientific_name": "Bupleurum chinense",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "伞形目", "family": "伞形科", "genus": "柴胡属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "bloom_months": [7, 8], "description": "多年生草本，根入药，北方山地阳坡。"}},
{"name": "北沙参", "scientific_name": "Glehnia littoralis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "伞形目", "family": "伞形科", "genus": "珊瑚菜属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 10, "height_max_cm": 30, "description": "多年生草本，根药用，北方沙地海边。"}},
{"name": "毒芹", "scientific_name": "Cicuta virosa",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "伞形目", "family": "伞形科", "genus": "毒芹属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "aquatic", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 80, "height_max_cm": 150, "description": "多年生草本，剧毒，水边沼泽。"}},

# ---------- 茄科补充 ----------
{"name": "茄子", "scientific_name": "Solanum melongena",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "茄目", "family": "茄科", "genus": "茄属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 150, "bloom_months": [6, 7, 8], "description": "一年生蔬菜，果实食用。"}},
{"name": "马铃薯", "scientific_name": "Solanum tuberosum",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "茄目", "family": "茄科", "genus": "茄属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "description": "一年生蔬菜，块茎（土豆）主食，北方广泛栽培。"}},
{"name": "枸杞", "scientific_name": "Lycium chinense",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "茄目", "family": "茄科", "genus": "枸杞属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 150, "bloom_months": [6, 7, 8], "description": "落叶灌木，果实（枸杞子）著名药材。"}},
{"name": "宁夏枸杞", "scientific_name": "Lycium barbarum",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "茄目", "family": "茄科", "genus": "枸杞属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 250, "bloom_months": [6, 7, 8], "description": "落叶灌木，宁夏枸杞道地产区，果药兼用。"}},
{"name": "曼陀罗", "scientific_name": "Datura stramonium",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "茄目", "family": "茄科", "genus": "曼陀罗属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 150, "bloom_months": [7, 8], "description": "一年生草本，有毒，花药用。"}},

# ---------- 葫芦科（新科）----------
{"name": "黄瓜", "scientific_name": "Cucumis sativus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "葫芦目", "family": "葫芦科", "genus": "黄瓜属"},
 "info": {"habit": "vine", "light": "full_sun", "water": "moist", "life_cycle": "annual", "foliage": "deciduous",
          "bloom_months": [6, 7, 8], "description": "一年生攀援草本，瓜果蔬菜。"}},
{"name": "西瓜", "scientific_name": "Citrullus lanatus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "葫芦目", "family": "葫芦科", "genus": "西瓜属"},
 "info": {"habit": "vine", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "description": "一年生蔓生草本，果为盛夏水果。"}},
{"name": "甜瓜", "scientific_name": "Cucumis melo",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "葫芦目", "family": "葫芦科", "genus": "黄瓜属"},
 "info": {"habit": "vine", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "description": "一年生蔓生草本，果实香甜。"}},
{"name": "南瓜", "scientific_name": "Cucurbita moschata",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "葫芦目", "family": "葫芦科", "genus": "南瓜属"},
 "info": {"habit": "vine", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "description": "一年生蔓生草本，果实与种子食用。"}},
{"name": "西葫芦", "scientific_name": "Cucurbita pepo",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "葫芦目", "family": "葫芦科", "genus": "南瓜属"},
 "info": {"habit": "vine", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "description": "一年生矮生或蔓生草本，嫩果蔬菜。"}},
{"name": "冬瓜", "scientific_name": "Benincasa hispida",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "葫芦目", "family": "葫芦科", "genus": "冬瓜属"},
 "info": {"habit": "vine", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "description": "一年生蔓生草本，大型果实蔬菜。"}},
{"name": "葫芦", "scientific_name": "Lagenaria siceraria",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "葫芦目", "family": "葫芦科", "genus": "葫芦属"},
 "info": {"habit": "vine", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "description": "一年生攀援草本，果实老熟作容器。"}},

# ---------- 报春花科/石竹科等小草本 ----------
{"name": "点地梅", "scientific_name": "Androsace umbellata",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "报春花目", "family": "报春花科", "genus": "点地梅属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 5, "height_max_cm": 20, "bloom_months": [4, 5], "description": "一年生矮小草本，早春路旁荒地白花。"}},
{"name": "大花石竹", "scientific_name": "Dianthus chinensis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "石竹科", "genus": "石竹属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 50, "bloom_months": [6, 7, 8], "description": "多年生草本，花艳丽，北方常见观赏与野生。"}},
{"name": "瞿麦", "scientific_name": "Dianthus superbus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "石竹科", "genus": "石竹属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 80, "bloom_months": [7, 8], "description": "多年生草本，花瓣丝裂，药用。"}},
{"name": "麦瓶草", "scientific_name": "Silene conoidea",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "石竹科", "genus": "蝇子草属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 80, "bloom_months": [5, 6], "description": "一年生草本，麦田常见。"}},
{"name": "繁缕", "scientific_name": "Stellaria media",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "石竹科", "genus": "繁缕属"},
 "info": {"habit": "herb", "light": "half_shade", "water": "moist", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 10, "height_max_cm": 40, "bloom_months": [4, 5, 6], "description": "一年生草本，田野湿地常见。"}},
{"name": "紫花地丁", "scientific_name": "Viola yedoensis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "堇菜目", "family": "堇菜科", "genus": "堇菜属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 5, "height_max_cm": 15, "bloom_months": [3, 4, 5], "description": "多年生矮小草本，早春紫花，全草药用。"}},
{"name": "斑叶堇菜", "scientific_name": "Viola variegata",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "堇菜目", "family": "堇菜科", "genus": "堇菜属"},
 "info": {"habit": "herb", "light": "half_shade", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 5, "height_max_cm": 20, "bloom_months": [4, 5], "description": "多年生草本，叶面有斑纹，北方山地林下。"}},
{"name": "猪毛菜", "scientific_name": "Salsola collina",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "苋科", "genus": "猪毛菜属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "description": "一年生草本，耐盐碱，西北盐碱地常见。"}},
{"name": "灰绿藜", "scientific_name": "Chenopodium glaucum",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "苋科", "genus": "藜属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 60, "description": "一年生草本，盐碱地常见杂草。"}},

# ---------- 百合科补充（单子叶）----------
{"name": "韭菜", "scientific_name": "Allium tuberosum",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "百合科", "genus": "葱属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 50, "description": "多年生草本，叶作蔬菜。"}},
{"name": "大葱", "scientific_name": "Allium fistulosum",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "百合科", "genus": "葱属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 100, "description": "多年生草本，北方大葱著名。"}},
{"name": "洋葱", "scientific_name": "Allium cepa",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "百合科", "genus": "葱属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "biennial", "foliage": "deciduous",
          "description": "鳞茎蔬菜，全球广泛栽培。"}},
{"name": "蒜", "scientific_name": "Allium sativum",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "百合科", "genus": "葱属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "description": "一年生草本，鳞茎（蒜头）调味。"}},
{"name": "野韭", "scientific_name": "Allium ramosum",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "百合科", "genus": "葱属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 50, "description": "多年生草本，山韭野菜，北方草原山地。"}},
{"name": "山丹", "scientific_name": "Lilium pumilum",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "百合科", "genus": "百合属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 60, "bloom_months": [6, 7], "description": "多年生草本，红花下垂，鳞茎食用，北方草原。"}},
{"name": "卷丹", "scientific_name": "Lilium lancifolium",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "百合科", "genus": "百合属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 80, "height_max_cm": 150, "bloom_months": [6, 7], "description": "多年生草本，橙红花有紫斑，鳞茎食用。"}},
{"name": "铃兰", "scientific_name": "Convallaria majalis",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "百合科", "genus": "铃兰属"},
 "info": {"habit": "herb", "light": "half_shade", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 40, "bloom_months": [5, 6], "description": "多年生草本，白色钟形花芳香，林下阴湿。"}},
{"name": "黄精", "scientific_name": "Polygonatum sibiricum",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "百合科", "genus": "黄精属"},
 "info": {"habit": "herb", "light": "half_shade", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 120, "bloom_months": [5, 6], "description": "多年生草本，根茎补益中药，北方林下。"}},
{"name": "玉竹", "scientific_name": "Polygonatum odoratum",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "百合科", "genus": "黄精属"},
 "info": {"habit": "herb", "light": "half_shade", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 80, "bloom_months": [5, 6], "description": "多年生草本，根茎药用，北方林下常见。"}},
{"name": "知母", "scientific_name": "Anemarrhena asphodeloides",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "百合科", "genus": "知母属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 120, "bloom_months": [6, 7], "description": "多年生草本，根茎清热中药，北方草原山地。"}},
{"name": "芦荟", "scientific_name": "Aloe vera",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "百合科", "genus": "芦荟属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 30, "height_max_cm": 80, "description": "多年生常绿肉质草本，栽培药用观赏。"}},

# ---------- 鸢尾/其他单子叶 ----------
{"name": "马蔺", "scientific_name": "Iris lactea",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "鸢尾科", "genus": "鸢尾属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 60, "bloom_months": [5, 6], "description": "多年生草本，耐盐碱，北方路旁荒地常见。"}},
{"name": "射干", "scientific_name": "Belamcanda chinensis",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "鸢尾科", "genus": "射干属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 120, "bloom_months": [6, 7, 8], "description": "多年生草本，橙红花有斑点，根茎药用。"}},
{"name": "花菖蒲", "scientific_name": "Iris ensata",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "鸢尾科", "genus": "鸢尾属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 100, "bloom_months": [6, 7], "description": "多年生草本，湿地观赏鸢尾。"}},
{"name": "香蒲", "scientific_name": "Typha orientalis",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "香蒲目", "family": "香蒲科", "genus": "香蒲属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "aquatic", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 200, "bloom_months": [5, 6, 7], "description": "多年生水生草本，蒲棒（花序）常见，湿地。"}},
{"name": "荻", "scientific_name": "Triarrhena sacchariflora",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "禾本目", "family": "禾本科", "genus": "荻属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 250, "bloom_months": [8, 9], "description": "多年生草本，秋穗如荻花，湿地常见。"}},
{"name": "拂子茅", "scientific_name": "Calamagrostis epigeios",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "禾本目", "family": "禾本科", "genus": "拂子茅属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 80, "height_max_cm": 150, "bloom_months": [7, 8], "description": "多年生草本，河岸草甸常见。"}},
{"name": "白羊草", "scientific_name": "Bothriochloa ischaemum",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "禾本目", "family": "禾本科", "genus": "孔颖草属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "bloom_months": [7, 8, 9], "description": "多年生草本，华北山地草原优势禾草。"}},
{"name": "针茅", "scientific_name": "Stipa capillata",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "禾本目", "family": "禾本科", "genus": "针茅属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 100, "bloom_months": [6, 7], "description": "多年生草本，内蒙古草原典型禾草。"}},
{"name": "羊草", "scientific_name": "Leymus chinensis",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "禾本目", "family": "禾本科", "genus": "赖草属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 100, "bloom_months": [6, 7], "description": "多年生草本，东北华北草原重要牧草。"}},
{"name": "披碱草", "scientific_name": "Elymus dahuricus",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "禾本目", "family": "禾本科", "genus": "披碱草属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 60, "height_max_cm": 140, "bloom_months": [7, 8], "description": "多年生草本，北方草原牧草。"}},

# ---------- 百合目补充球根花卉 ----------
{"name": "郁金香", "scientific_name": "Tulipa gesneriana",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "百合科", "genus": "郁金香属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 50, "bloom_months": [4, 5], "description": "多年生球根花卉，春季公园花海。"}},
{"name": "风信子", "scientific_name": "Hyacinthus orientalis",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "百合科", "genus": "风信子属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 40, "bloom_months": [3, 4], "description": "多年生球根花卉，早春室内外观赏。"}},
{"name": "葱兰", "scientific_name": "Zephyranthes candida",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "石蒜科", "genus": "葱莲属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 15, "height_max_cm": 30, "bloom_months": [6, 7, 8], "description": "多年生球根草本，白花，北方盆栽或花坛。"}},
]
