# -*- coding: utf-8 -*-
# 批次 5：北方果树/浆果、藤本、旱生沙生植物、草本花卉补充（约 90 种）

P = "被子植物门"
DIC = "双子叶植物纲"
MONO = "单子叶植物纲"

PLANTS = [
# ---------- 蔷薇科果树补充 ----------
{"name": "秋子梨", "scientific_name": "Pyrus ussuriensis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "梨属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 800, "height_max_cm": 1500, "bloom_months": [5], "description": "落叶乔木，东北梨栽培品种主要亲本。"}},
{"name": "京白梨", "scientific_name": "Pyrus ussuriensis cv.",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "梨属"},
 "rank": "cultivar",
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 500, "height_max_cm": 1000, "description": "北京特产梨品种，果皮薄肉细。"}},
{"name": "沙果", "scientific_name": "Malus asiatica",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "苹果属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 300, "height_max_cm": 800, "description": "落叶小乔木，果味酸甜，北方传统果树。"}},
{"name": "海棠果", "scientific_name": "Malus prunifolia",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "苹果属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 300, "height_max_cm": 800, "bloom_months": [4, 5], "description": "落叶小乔木，观花赏果，苹果砧木。"}},
{"name": "白梨", "scientific_name": "Pyrus bretschneideri",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "梨属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 500, "height_max_cm": 1500, "description": "落叶乔木，华北主栽梨种。"}},

# ---------- 猕猴桃科 / 葡萄科补充 ----------
{"name": "软枣猕猴桃", "scientific_name": "Actinidia arguta",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "山茶目", "family": "猕猴桃科", "genus": "猕猴桃属"},
 "info": {"habit": "vine", "light": "half_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 300, "height_max_cm": 1000, "bloom_months": [6], "description": "木质藤本，果可食，东北林区特产。"}},
{"name": "狗枣猕猴桃", "scientific_name": "Actinidia kolomikta",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "山茶目", "family": "猕猴桃科", "genus": "猕猴桃属"},
 "info": {"habit": "vine", "light": "half_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 300, "height_max_cm": 1000, "bloom_months": [6], "description": "木质藤本，观赏与食用。"}},
{"name": "山葡萄", "scientific_name": "Vitis amurensis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "鼠李目", "family": "葡萄科", "genus": "葡萄属"},
 "info": {"habit": "vine", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 300, "height_max_cm": 1500, "bloom_months": [5, 6], "description": "木质藤本，抗寒砧木，果酿酒。"}},
{"name": "爬山虎", "scientific_name": "Parthenocissus tricuspidata",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "鼠李目", "family": "葡萄科", "genus": "爬山虎属"},
 "info": {"habit": "vine", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 300, "height_max_cm": 2000, "description": "木质藤本，秋叶红，墙面绿化。"}},

# ---------- 沙生旱生植物（西北特色）----------
{"name": "沙棘", "scientific_name": "Hippophae rhamnoides",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "鼠李目", "family": "胡颓子科", "genus": "沙棘属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 500, "bloom_months": [4, 5], "description": "落叶灌木，耐旱耐盐碱，橙红浆果富含维C，西北水土保持。"}},
{"name": "沙枣", "scientific_name": "Elaeagnus angustifolia",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "鼠李目", "family": "胡颓子科", "genus": "胡颓子属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 400, "height_max_cm": 1000, "bloom_months": [5], "description": "落叶乔木，叶银白，果可食，西北防风固沙。"}},
{"name": "胡颓子", "scientific_name": "Elaeagnus pungens",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "鼠李目", "family": "胡颓子科", "genus": "胡颓子属"},
 "info": {"habit": "shrub", "light": "half_sun", "water": "dry", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 100, "height_max_cm": 300, "description": "常绿灌木，叶背银色，观叶观果。"}},
{"name": "白刺", "scientific_name": "Nitraria tangutorum",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蒺藜目", "family": "蒺藜科", "genus": "白刺属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 200, "bloom_months": [5, 6], "description": "落叶灌木，极耐旱耐盐，西北荒漠固沙植物。"}},
{"name": "梭梭", "scientific_name": "Haloxylon ammodendron",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "苋科", "genus": "梭梭属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 200, "height_max_cm": 600, "description": "小乔木状灌木，荒漠固沙先锋，西北沙漠。"}},
{"name": "柽柳", "scientific_name": "Tamarix chinensis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "柽柳科", "genus": "柽柳属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 200, "height_max_cm": 500, "bloom_months": [5, 6, 7], "description": "落叶灌木，耐盐碱水湿，华北西北盐碱地绿化。"}},
{"name": "盐爪爪", "scientific_name": "Kalidium foliatum",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "苋科", "genus": "盐爪爪属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "description": "小灌木，肉质叶，极耐盐碱，盐碱滩标志植物。"}},
{"name": "骆驼刺", "scientific_name": "Alhagi sparsifolia",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "豆目", "family": "豆科", "genus": "骆驼刺属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 150, "bloom_months": [6, 7], "description": "多年生半灌木，荒漠绿洲常见。"}},
{"name": "沙葱", "scientific_name": "Allium mongolicum",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "百合科", "genus": "葱属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 10, "height_max_cm": 30, "bloom_months": [7, 8], "description": "多年生草本，沙地野生葱类，西北草原野菜。"}},

# ---------- 更多北方花灌木 ----------
{"name": "紫叶小檗", "scientific_name": "Berberis thunbergii var. atropurpurea",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "毛茛目", "family": "小檗科", "genus": "小檗属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 200, "bloom_months": [5], "description": "落叶灌木，紫红叶色，北方绿篱色块。"}},
{"name": "南天竹", "scientific_name": "Nandina domestica",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "毛茛目", "family": "小檗科", "genus": "南天竹属"},
 "info": {"habit": "shrub", "light": "half_shade", "water": "moderate", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 100, "height_max_cm": 300, "description": "常绿灌木，红叶红果，庭院观赏。"}},
{"name": "蜡梅", "scientific_name": "Chimonanthus praecox",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "樟目", "family": "蜡梅科", "genus": "蜡梅属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 200, "height_max_cm": 500, "bloom_months": [12, 1, 2], "description": "落叶灌木，严冬黄花芳香。"}},
{"name": "紫薇变种", "scientific_name": "Lagerstroemia indica",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "桃金娘目", "family": "千屈菜科", "genus": "紫薇属"},
 "rank": "cultivar",
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 300, "height_max_cm": 700, "bloom_months": [6, 7, 8, 9], "description": "落叶灌木或小乔木，夏秋红花，北方栽培。"}},

# ---------- 果树补充 ----------
{"name": "板栗-丹东板栗", "scientific_name": "Castanea mollissima",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "壳斗目", "family": "壳斗科", "genus": "栗属"},
 "rank": "cultivar",
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 500, "height_max_cm": 1000, "description": "丹东地区板栗，北方著名产区。"}},
{"name": "毛榛子", "scientific_name": "Corylus heterophylla",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "壳斗目", "family": "桦木科", "genus": "榛属"},
 "rank": "variety",
 "info": {"habit": "shrub", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 300, "description": "灌木，榛子坚果。"}},

# 大枣变种
{"name": "枣-圆铃枣", "scientific_name": "Ziziphus jujuba cv.",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "鼠李目", "family": "鼠李科", "genus": "枣属"},
 "rank": "cultivar",
 "info": {"habit": "tree", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 500, "height_max_cm": 1000, "description": "山东/河北枣品种，果大肉厚。"}},

# ---------- 其他常见观赏/蔬菜/草本 ----------
{"name": "薰衣草", "scientific_name": "Lavandula angustifolia",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "唇形科", "genus": "薰衣草属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 30, "height_max_cm": 90, "bloom_months": [6, 7], "description": "半灌木，芳香植物，北方香草园栽培。"}},
{"name": "迷迭香", "scientific_name": "Rosmarinus officinalis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "唇形科", "genus": "迷迭香属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 50, "height_max_cm": 150, "description": "常绿灌木，香料植物，室内外栽培。"}},
{"name": "罗勒", "scientific_name": "Ocimum basilicum",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "唇形科", "genus": "罗勒属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 80, "description": "一年生草本，芳香调料。"}},
{"name": "薄荷-留兰香", "scientific_name": "Mentha spicata",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "唇形科", "genus": "薄荷属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 80, "description": "多年生草本，留兰香型薄荷，芳香作物。"}},
{"name": "紫苏", "scientific_name": "Perilla frutescens",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "唇形科", "genus": "紫苏属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 150, "bloom_months": [7, 8], "description": "一年生草本，叶紫色调味，种子榨油。"}},
{"name": "荆条", "scientific_name": "Vitex negundo var. heterophylla",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "唇形科", "genus": "牡荆属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 300, "bloom_months": [7, 8], "description": "落叶灌木，北方荒山灌丛优势种，荆条蜜源。"}},

# ---------- 木本观赏补充 ----------
{"name": "七叶树", "scientific_name": "Aesculus chinensis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "无患子目", "family": "七叶树科", "genus": "七叶树属"},
 "info": {"habit": "tree", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1000, "height_max_cm": 2500, "bloom_months": [5, 6], "description": "落叶乔木，掌状复叶，白花塔状，华北名木。"}},
{"name": "文冠果", "scientific_name": "Xanthoceras sorbifolium",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "无患子目", "family": "无患子科", "genus": "文冠果属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 200, "height_max_cm": 500, "bloom_months": [4, 5], "description": "落叶灌木或小乔木，北方木本油料树种。"}},
{"name": "栾树-黄山栾", "scientific_name": "Koelreuteria bipinnata",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "无患子目", "family": "无患子科", "genus": "栾树属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1000, "height_max_cm": 2000, "bloom_months": [7, 8], "description": "落叶乔木，金黄秋花与红果。"}},
{"name": "火炬漆", "scientific_name": "Rhus chinensis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "无患子目", "family": "漆树科", "genus": "盐肤木属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 400, "bloom_months": [7, 8], "description": "落叶灌木，五倍子蚜虫寄主。"}},

# ---------- 秋海棠/天南星等盆栽 ----------
{"name": "一串铃", "scientific_name": "Impatiens balsamina",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "杜鹃花目", "family": "凤仙花科", "genus": "凤仙花属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moist", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 80, "bloom_months": [7, 8, 9], "description": "一年生草本（凤仙花），北方庭园常见。"}},
{"name": "何氏凤仙", "scientific_name": "Impatiens walleriana",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "杜鹃花目", "family": "凤仙花科", "genus": "凤仙花属"},
 "info": {"habit": "herb", "light": "half_shade", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 60, "bloom_months": [6, 7, 8], "description": "多年生常作一年生，盆栽花坛花卉。"}},
{"name": "四季海棠", "scientific_name": "Begonia semperflorens",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "葫芦目", "family": "秋海棠科", "genus": "秋海棠属"},
 "info": {"habit": "herb", "light": "half_shade", "water": "moderate", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 15, "height_max_cm": 40, "bloom_months": [5, 6, 7, 8], "description": "多年生草本，四季开花，北方盆栽花坛。"}},
{"name": "龟背竹", "scientific_name": "Monstera deliciosa",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "天南星目", "family": "天南星科", "genus": "龟背竹属"},
 "info": {"habit": "vine", "light": "half_shade", "water": "moist", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 100, "height_max_cm": 300, "description": "常绿藤本，叶有孔裂，著名室内观叶植物。"}},
{"name": "绿萝", "scientific_name": "Epipremnum aureum",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "天南星目", "family": "天南星科", "genus": "麒麟叶属"},
 "info": {"habit": "vine", "light": "half_shade", "water": "moist", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 100, "height_max_cm": 500, "description": "常绿藤本，室内垂吊观叶。"}},

# ---------- 松柏类补充观叶 ----------
{"name": "龙柏", "scientific_name": "Juniperus chinensis 'Kaizuka'",
 "path": {"kingdom": "植物界", "phylum": "裸子植物门", "class": "松杉纲", "order": "松杉目", "family": "柏科", "genus": "圆柏属"},
 "rank": "cultivar",
 "info": {"habit": "tree", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 300, "height_max_cm": 800, "description": "常绿乔木，枝盘旋如龙，北方园林造型树。"}},
{"name": "洒金柏", "scientific_name": "Platycladus orientalis 'Aurea'",
 "path": {"kingdom": "植物界", "phylum": "裸子植物门", "class": "松杉纲", "order": "松杉目", "family": "柏科", "genus": "侧柏属"},
 "rank": "cultivar",
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "evergreen",
          "height_min_cm": 100, "height_max_cm": 300, "description": "常绿灌木，金黄叶色，绿篱色块。"}},

# ---------- 补充落叶乔木 ----------
{"name": "椴树", "scientific_name": "Tilia tuan",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "锦葵目", "family": "椴树科", "genus": "椴树属"},
 "info": {"habit": "tree", "light": "half_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1000, "height_max_cm": 2500, "bloom_months": [6, 7], "description": "落叶乔木，优良蜜源与用材，东北林区。"}},
{"name": "糠椴", "scientific_name": "Tilia mandshurica",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "锦葵目", "family": "椴树科", "genus": "椴树属"},
 "info": {"habit": "tree", "light": "half_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1000, "height_max_cm": 2000, "bloom_months": [6, 7], "description": "落叶乔木，东北林区用材与蜜源。"}},
{"name": "青桐", "scientific_name": "Firmiana simplex",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "锦葵目", "family": "梧桐科", "genus": "梧桐属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 800, "height_max_cm": 2000, "description": "落叶乔木（梧桐），华北庭荫树。"}},

# ---------- 耐寒草本花卉补充 ----------
{"name": "萱草-大花萱草", "scientific_name": "Hemerocallis hybrida",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "百合科", "genus": "萱草属"},
 "rank": "cultivar",
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 40, "height_max_cm": 90, "bloom_months": [6, 7], "description": "多年生宿根花卉，花大色艳，北方园林。"}},
{"name": "玉簪-白萼", "scientific_name": "Hosta plantaginea",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "百合科", "genus": "玉簪属"},
 "rank": "form",
 "info": {"habit": "herb", "light": "shade", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 60, "bloom_months": [8, 9], "description": "多年生草本，耐阴白花芳香。"}},
{"name": "鸢尾-德国鸢尾", "scientific_name": "Iris germanica",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "百合目", "family": "鸢尾科", "genus": "鸢尾属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 40, "height_max_cm": 90, "bloom_months": [5, 6], "description": "多年生宿根花卉，花大，北方栽培。"}},

# 石竹科补充 + 罂粟科
{"name": "虞美人", "scientific_name": "Papaver rhoeas",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "毛茛目", "family": "罂粟科", "genus": "罂粟属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 80, "bloom_months": [5, 6], "description": "一年生草本，花色艳丽，观赏。"}},
{"name": "荷包牡丹", "scientific_name": "Dicentra spectabilis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "毛茛目", "family": "罂粟科", "genus": "荷包牡丹属"},
 "info": {"habit": "herb", "light": "half_shade", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 60, "bloom_months": [4, 5, 6], "description": "多年生草本，花如荷包，北方庭院。"}},
{"name": "延胡索", "scientific_name": "Corydalis yanhusuo",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "毛茛目", "family": "罂粟科", "genus": "紫堇属"},
 "info": {"habit": "herb", "light": "half_shade", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 15, "height_max_cm": 40, "bloom_months": [4, 5], "description": "多年生草本，块茎止痛中药，北方栽培。"}},

# ---------- 补充单子叶类 ----------
{"name": "玉米-甜玉米", "scientific_name": "Zea mays",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "禾本目", "family": "禾本科", "genus": "玉蜀黍属"},
 "rank": "cultivar",
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 150, "height_max_cm": 250, "description": "甜玉米品种。"}},
{"name": "高粱", "scientific_name": "Sorghum bicolor",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "禾本目", "family": "禾本科", "genus": "高粱属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 300, "description": "一年生草本，北方旱粮作物。"}},
{"name": "粟-谷子", "scientific_name": "Setaria italica",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "禾本目", "family": "禾本科", "genus": "狗尾草属"},
 "rank": "cultivar",
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 150, "description": "一年生草本（小米），北方旱作谷物。"}},
{"name": "黍", "scientific_name": "Panicum miliaceum",
 "path": {"kingdom": "植物界", "phylum": P, "class": MONO, "order": "禾本目", "family": "禾本科", "genus": "黍属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 60, "height_max_cm": 150, "description": "一年生草本（糜子/黄米），北方旱作。"}},
{"name": "荞麦", "scientific_name": "Fagopyrum esculentum",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "蓼科", "genus": "荞麦属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 40, "height_max_cm": 100, "bloom_months": [7, 8, 9], "description": "一年生草本，北方山区杂粮与蜜源。"}},

# ---------- 花灌木/藤本补 ----------
{"name": "月季-丰花月季", "scientific_name": "Rosa hybrida",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "蔷薇属"},
 "rank": "cultivar",
 "info": {"habit": "shrub", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 150, "bloom_months": [5, 6, 7, 8, 9], "description": "灌木，北方四季开花不断。"}},
{"name": "木香", "scientific_name": "Rosa banksiae",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "蔷薇属"},
 "info": {"habit": "vine", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 200, "height_max_cm": 600, "bloom_months": [4, 5], "description": "半常绿攀援灌木，白花芳香，北方庭院。"}},
{"name": "金银花", "scientific_name": "Lonicera japonica",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "川续断目", "family": "忍冬科", "genus": "忍冬属"},
 "info": {"habit": "vine", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "semi_evergreen",
          "height_min_cm": 200, "height_max_cm": 500, "bloom_months": [5, 6, 7], "description": "半常绿藤本，花蕾药材（金银花），北方栽培。"}},
]
