# -*- coding: utf-8 -*-
# 批次 7：补齐到 300+（约 12 条）

P = "被子植物门"
DIC = "双子叶植物纲"
MONO = "单子叶植物纲"

PLANTS = [
{"name": "大花溲疏", "scientific_name": "Deutzia grandiflora",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "山茱萸目", "family": "绣球科", "genus": "溲疏属"},
 "info": {"habit": "shrub", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 200, "bloom_months": [5, 6], "description": "落叶灌木，白花，北方山地灌丛。"}},
{"name": "绣球", "scientific_name": "Hydrangea macrophylla",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "山茱萸目", "family": "绣球科", "genus": "绣球属"},
 "info": {"habit": "shrub", "light": "half_shade", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 300, "bloom_months": [6, 7, 8], "description": "落叶灌木，花球美丽，庭院盆栽。"}},
{"name": "八仙花", "scientific_name": "Hydrangea macrophylla",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "山茱萸目", "family": "绣球科", "genus": "绣球属"},
 "rank": "cultivar",
 "info": {"habit": "shrub", "light": "half_shade", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 200, "bloom_months": [6, 7], "description": "绣球品种。"}},
{"name": "假龙头", "scientific_name": "Physostegia virginiana",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "唇形科", "genus": "假龙头属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 60, "height_max_cm": 120, "bloom_months": [8, 9], "description": "多年生宿根花卉，粉紫花穗。"}},
{"name": "桔梗", "scientific_name": "Platycodon grandiflorus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "桔梗目", "family": "桔梗科", "genus": "桔梗属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "bloom_months": [7, 8], "description": "多年生草本，蓝紫钟形花，根药用，北方山地。"}},
{"name": "沙参", "scientific_name": "Adenophora stricta",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "桔梗目", "family": "桔梗科", "genus": "沙参属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 120, "bloom_months": [7, 8], "description": "多年生草本，根药用，北方山地。"}},
{"name": "轮叶沙参", "scientific_name": "Adenophora tetraphylla",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "桔梗目", "family": "桔梗科", "genus": "沙参属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 120, "bloom_months": [7, 8], "description": "多年生草本，四叶轮生。"}},
{"name": "风铃草", "scientific_name": "Campanula medium",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "桔梗目", "family": "桔梗科", "genus": "风铃草属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moderate", "life_cycle": "biennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 80, "bloom_months": [6, 7], "description": "二年生草本，铃铛花，花坛。"}},
{"name": "紫斑风铃草", "scientific_name": "Campanula punctata",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "桔梗目", "family": "桔梗科", "genus": "风铃草属"},
 "info": {"habit": "herb", "light": "half_shade", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 80, "bloom_months": [6, 7, 8], "description": "多年生草本，钟形花有紫斑，北方山地林缘。"}},
{"name": "王不留行", "scientific_name": "Vaccaria hispanica",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "石竹科", "genus": "王不留行属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 80, "bloom_months": [5, 6, 7], "description": "一年生草本，麦田杂草，种子药用。"}},
{"name": "紫茉莉", "scientific_name": "Mirabilis jalapa",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "石竹目", "family": "紫茉莉科", "genus": "紫茉莉属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 100, "bloom_months": [6, 7, 8], "description": "多年生草本，傍晚开花，庭院常见。"}},
]
