# -*- coding: utf-8 -*-
# 批次 2：蔷薇科花灌木/果树补充、豆科、木犀科等北方花木（约 65 种）

P = "被子植物门"
DIC = "双子叶植物纲"

PLANTS = [
# ---------- 蔷薇科补充 ----------
{"name": "山桃", "scientific_name": "Prunus davidiana",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "桃属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 400, "height_max_cm": 1000, "bloom_months": [3, 4], "description": "落叶乔木，早春粉花满树，华北山地野生及绿化树种。"}},
{"name": "山杏", "scientific_name": "Prunus sibirica",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "杏属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 300, "height_max_cm": 800, "bloom_months": [4], "description": "落叶小乔木，耐旱耐寒，北方荒山绿化先锋树种。"}},
{"name": "山荆子", "scientific_name": "Malus baccata",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "苹果属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 500, "height_max_cm": 1400, "bloom_months": [5], "description": "落叶乔木，苹果砧木，果小可食，秋叶美观。"}},
{"name": "花红", "scientific_name": "Malus asiatica",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "苹果属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 300, "height_max_cm": 800, "description": "落叶小乔木，果实可食，北方栽培果树。"}},
{"name": "杜梨", "scientific_name": "Pyrus betulifolia",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "梨属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 500, "height_max_cm": 1000, "description": "落叶乔木，梨砧木，耐旱耐盐碱。"}},
{"name": "欧李", "scientific_name": "Prunus humilis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "樱桃属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 150, "bloom_months": [4, 5], "description": "灌木，果实钙含量高，北方野生及栽培。"}},
{"name": "榆叶梅", "scientific_name": "Prunus triloba",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "桃属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 200, "height_max_cm": 400, "bloom_months": [4], "description": "落叶灌木，早春粉花繁密，北方园林常见。"}},
{"name": "毛樱桃", "scientific_name": "Prunus tomentosa",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "樱桃属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 200, "height_max_cm": 300, "bloom_months": [4], "description": "落叶灌木，果红可食，华北常见。"}},
{"name": "稠李", "scientific_name": "Prunus padus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "稠李属"},
 "info": {"habit": "tree", "light": "half_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 800, "height_max_cm": 1500, "bloom_months": [4, 5], "description": "落叶乔木，白花总状花序，东北华北林区常见。"}},
{"name": "紫叶李", "scientific_name": "Prunus cerasifera f. atropurpurea",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "李属"},
 "rank": "form",
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 300, "height_max_cm": 800, "bloom_months": [4], "description": "落叶小乔木，紫红叶色，北方园林彩叶树种。"}},
{"name": "珍珠梅", "scientific_name": "Sorbaria sorbifolia",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "珍珠梅属"},
 "info": {"habit": "shrub", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 250, "bloom_months": [6, 7, 8], "description": "落叶灌木，白花圆锥花序，耐阴，华北常见绿篱。"}},
{"name": "三裂绣线菊", "scientific_name": "Spiraea trilobata",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "绣线菊属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 200, "bloom_months": [5], "description": "落叶灌木，白花伞形花序，华北山地常见。"}},
{"name": "金山绣线菊", "scientific_name": "Spiraea japonica 'Gold Mound'",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "绣线菊属"},
 "rank": "cultivar",
 "info": {"habit": "shrub", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 100, "bloom_months": [6, 7], "description": "栽培品种，春季新叶金黄，花粉色。"}},
{"name": "玫瑰", "scientific_name": "Rosa rugosa",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "蔷薇属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 200, "bloom_months": [5, 6, 7], "description": "落叶灌木，芳香，花瓣可食，北方常见栽培。"}},
{"name": "黄刺玫", "scientific_name": "Rosa xanthina",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "蔷薇属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 150, "height_max_cm": 250, "bloom_months": [5], "description": "落叶灌木，黄花重瓣，华北园林及山地常见。"}},
{"name": "水栒子", "scientific_name": "Cotoneaster multiflorus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "栒子属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 200, "height_max_cm": 400, "bloom_months": [5], "description": "落叶灌木，白花繁密，红果挂枝，北方常见。"}},
{"name": "毛叶水栒子", "scientific_name": "Cotoneaster submultiflorus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "栒子属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 150, "height_max_cm": 300, "description": "落叶灌木，叶背有毛，华北山地阳坡常见。"}},
{"name": "山楂叶悬钩子", "scientific_name": "Rubus crataegifolius",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "悬钩子属"},
 "info": {"habit": "shrub", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 200, "bloom_months": [5, 6], "description": "灌木，果实可食，东北华北山地常见。"}},
{"name": "委陵菜", "scientific_name": "Potentilla chinensis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "委陵菜属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 20, "height_max_cm": 60, "bloom_months": [6, 7], "description": "多年生草本，黄花，北方旷野常见。"}},
{"name": "鹅绒委陵菜", "scientific_name": "Potentilla anserina",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "委陵菜属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 10, "height_max_cm": 40, "bloom_months": [6, 7, 8], "description": "匍匐多年生草本，叶背银白绢毛，湿地常见。"}},
{"name": "地榆", "scientific_name": "Sanguisorba officinalis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "蔷薇目", "family": "蔷薇科", "genus": "地榆属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 150, "bloom_months": [6, 7, 8], "description": "多年生草本，暗红花穗，北方山地草甸常见药用植物。"}},

# ---------- 豆科（北方常见）----------
{"name": "紫穗槐", "scientific_name": "Amorpha fruticosa",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "豆目", "family": "豆科", "genus": "紫穗槐属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous", "growth_rate": "fast",
          "height_min_cm": 150, "height_max_cm": 400, "bloom_months": [5, 6], "description": "落叶灌木，耐盐碱瘠薄，北方水土保持与绿肥树种。"}},
{"name": "胡枝子", "scientific_name": "Lespedeza bicolor",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "豆目", "family": "豆科", "genus": "胡枝子属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 250, "bloom_months": [7, 8], "description": "落叶灌木，紫红花序，北方荒山灌丛优势种。"}},
{"name": "柠条锦鸡儿", "scientific_name": "Caragana korshinskii",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "豆目", "family": "豆科", "genus": "锦鸡儿属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 150, "height_max_cm": 300, "bloom_months": [5], "description": "落叶灌木，极耐旱，西北荒漠草原固沙造林先锋。"}},
{"name": "小叶锦鸡儿", "scientific_name": "Caragana microphylla",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "豆目", "family": "豆科", "genus": "锦鸡儿属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 200, "bloom_months": [5, 6], "description": "落叶灌木，东北西部草原常见豆科饲用灌木。"}},
{"name": "红花锦鸡儿", "scientific_name": "Caragana rosea",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "豆目", "family": "豆科", "genus": "锦鸡儿属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 200, "bloom_months": [4, 5], "description": "落叶灌木，花黄色带红晕，华北山地阳坡。"}},
{"name": "刺槐变种-无刺槐", "scientific_name": "Robinia pseudoacacia var. inermis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "豆目", "family": "豆科", "genus": "刺槐属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 500, "height_max_cm": 1500, "description": "落叶乔木，无刺品种，华北行道与用材。"}},
{"name": "朝鲜槐", "scientific_name": "Maackia amurensis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "豆目", "family": "豆科", "genus": "马鞍树属"},
 "info": {"habit": "tree", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1000, "height_max_cm": 2500, "bloom_months": [6, 7], "description": "落叶乔木，材质硬重，东北林区珍贵用材树种。"}},
{"name": "苦参", "scientific_name": "Sophora flavescens",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "豆目", "family": "豆科", "genus": "槐属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 80, "height_max_cm": 200, "bloom_months": [6, 7], "description": "灌木，根苦药用，北方山坡常见。"}},
{"name": "紫苜蓿", "scientific_name": "Medicago sativa",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "豆目", "family": "豆科", "genus": "苜蓿属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 40, "height_max_cm": 100, "bloom_months": [5, 6, 7], "description": "多年生草本，优质牧草，北方广泛栽培。"}},
{"name": "草木樨", "scientific_name": "Melilotus officinalis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "豆目", "family": "豆科", "genus": "草木樨属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "biennial", "foliage": "deciduous",
          "height_min_cm": 80, "height_max_cm": 200, "bloom_months": [6, 7, 8], "description": "二年生草本，绿肥与蜜源植物，路边常见。"}},
{"name": "歪头菜", "scientific_name": "Vicia unijuga",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "豆目", "family": "豆科", "genus": "野豌豆属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 30, "height_max_cm": 100, "bloom_months": [6, 7], "description": "多年生草本，蓝紫花，北方山地林缘常见。"}},
{"name": "山野豌豆", "scientific_name": "Vicia amoena",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "豆目", "family": "豆科", "genus": "野豌豆属"},
 "info": {"habit": "herb", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 120, "bloom_months": [6, 7, 8], "description": "多年生草本，优良牧草，北方山坡草地。"}},
{"name": "米口袋", "scientific_name": "Gueldenstaedtia verna",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "豆目", "family": "豆科", "genus": "米口袋属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 5, "height_max_cm": 20, "bloom_months": [4, 5], "description": "多年生矮小草本，紫红花，早春北方路边常见。"}},
{"name": "鸡眼草", "scientific_name": "Kummerowia striata",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "豆目", "family": "豆科", "genus": "鸡眼草属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "moderate", "life_cycle": "annual", "foliage": "deciduous",
          "height_min_cm": 10, "height_max_cm": 30, "bloom_months": [7, 8, 9], "description": "一年生草本，荒地路边常见。"}},
{"name": "二色棘豆", "scientific_name": "Oxytropis bicolor",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "豆目", "family": "豆科", "genus": "棘豆属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 10, "height_max_cm": 30, "bloom_months": [5, 6], "description": "多年生草本，黄紫双色花，华北旱地常见。"}},
{"name": "甘草", "scientific_name": "Glycyrrhiza uralensis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "豆目", "family": "豆科", "genus": "甘草属"},
 "info": {"habit": "herb", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 50, "height_max_cm": 150, "bloom_months": [6, 7, 8], "description": "多年生草本，根为著名中药，西北沙地常见。"}},

# ---------- 木犀科补充 ----------
{"name": "大叶白蜡", "scientific_name": "Fraxinus rhynchophylla",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "木犀科", "genus": "白蜡树属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1000, "height_max_cm": 2000, "description": "落叶乔木，东北华北常见用材与绿化树种。"}},
{"name": "水曲柳", "scientific_name": "Fraxinus mandschurica",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "木犀科", "genus": "白蜡树属"},
 "info": {"habit": "tree", "light": "half_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1500, "height_max_cm": 3000, "description": "落叶乔木，东北红松阔叶林珍贵用材树种。"}},
{"name": "花曲柳", "scientific_name": "Fraxinus chinensis var. rhynchophylla",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "木犀科", "genus": "白蜡树属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 1000, "height_max_cm": 2000, "description": "落叶乔木，华北常见，木材坚韧。"}},
{"name": "金钟花", "scientific_name": "Forsythia viridissima",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "木犀科", "genus": "连翘属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 150, "height_max_cm": 300, "bloom_months": [3, 4], "description": "落叶灌木，早春黄花，与连翘相似，园林常见。"}},
{"name": "暴马丁香", "scientific_name": "Syringa reticulata subsp. amurensis",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "木犀科", "genus": "丁香属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 600, "height_max_cm": 1500, "bloom_months": [6, 7], "description": "落叶乔木，白花，东北华北山地沟谷常见。"}},
{"name": "小叶丁香", "scientific_name": "Syringa microphylla",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "木犀科", "genus": "丁香属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 150, "height_max_cm": 300, "bloom_months": [5, 6], "description": "落叶灌木，花紫红，叶小，北方山地。"}},
{"name": "流苏树", "scientific_name": "Chionanthus retusus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "木犀科", "genus": "流苏树属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 500, "height_max_cm": 2000, "bloom_months": [5], "description": "落叶乔木，白花如流苏，华北园林珍稀树种。"}},
{"name": "雪柳", "scientific_name": "Fontanesia fortunei",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "唇形目", "family": "木犀科", "genus": "雪柳属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 200, "height_max_cm": 500, "bloom_months": [5, 6], "description": "落叶灌木，绿篱与水土保持，华北常见。"}},

# ---------- 忍冬科（新科）----------
{"name": "金银忍冬", "scientific_name": "Lonicera maackii",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "川续断目", "family": "忍冬科", "genus": "忍冬属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 200, "height_max_cm": 500, "bloom_months": [5, 6], "description": "落叶灌木，白花后转黄，红果经冬，北方园林常见。"}},
{"name": "蓝靛果忍冬", "scientific_name": "Lonicera caerulea",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "川续断目", "family": "忍冬科", "genus": "忍冬属"},
 "info": {"habit": "shrub", "light": "half_sun", "water": "moist", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 200, "bloom_months": [5], "description": "落叶灌木，蓝紫浆果可食，东北林区珍贵果树。"}},
{"name": "接骨木", "scientific_name": "Sambucus williamsii",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "川续断目", "family": "忍冬科", "genus": "接骨木属"},
 "info": {"habit": "shrub", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 300, "height_max_cm": 600, "bloom_months": [5, 6], "description": "落叶灌木或小乔木，民间药用，北方常见。"}},
{"name": "荚蒾", "scientific_name": "Viburnum dilatatum",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "川续断目", "family": "忍冬科", "genus": "荚蒾属"},
 "info": {"habit": "shrub", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 200, "height_max_cm": 300, "bloom_months": [5, 6], "description": "落叶灌木，红果观赏，华北山地林下。"}},
{"name": "天目琼花", "scientific_name": "Viburnum sargentii",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "川续断目", "family": "忍冬科", "genus": "荚蒾属"},
 "info": {"habit": "shrub", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 200, "height_max_cm": 400, "bloom_months": [5, 6], "description": "落叶灌木，白花外圈不孕花，红果，东北华北园林。"}},
{"name": "锦带花", "scientific_name": "Weigela florida",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "川续断目", "family": "忍冬科", "genus": "锦带花属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 150, "height_max_cm": 300, "bloom_months": [4, 5, 6], "description": "落叶灌木，花紫红漏斗形，北方园林春花灌木。"}},

# ---------- 其他常见灌木 ----------
{"name": "黄栌", "scientific_name": "Cotinus coggygria",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "无患子目", "family": "漆树科", "genus": "黄栌属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 300, "height_max_cm": 800, "bloom_months": [5, 6], "description": "落叶灌木，秋叶变红，北京香山红叶主要树种。"}},
{"name": "火炬树", "scientific_name": "Rhus typhina",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "无患子目", "family": "漆树科", "genus": "盐肤木属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 500, "height_max_cm": 1200, "description": "落叶小乔木，秋叶红艳，引种绿化树种。"}},
{"name": "卫矛", "scientific_name": "Euonymus alatus",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "卫矛目", "family": "卫矛科", "genus": "卫矛属"},
 "info": {"habit": "shrub", "light": "half_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 200, "height_max_cm": 400, "bloom_months": [5], "description": "落叶灌木，枝有木栓翅，秋叶红，北方常见。"}},
{"name": "鼠李", "scientific_name": "Rhamnus davurica",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "鼠李目", "family": "鼠李科", "genus": "鼠李属"},
 "info": {"habit": "tree", "light": "full_sun", "water": "moderate", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 300, "height_max_cm": 1000, "description": "落叶灌木或小乔木，东北华北山地灌丛常见。"}},
{"name": "酸枣", "scientific_name": "Ziziphus jujuba var. spinosa",
 "path": {"kingdom": "植物界", "phylum": P, "class": DIC, "order": "鼠李目", "family": "鼠李科", "genus": "枣属"},
 "info": {"habit": "shrub", "light": "full_sun", "water": "dry", "life_cycle": "perennial", "foliage": "deciduous",
          "height_min_cm": 100, "height_max_cm": 300, "bloom_months": [5, 6], "description": "落叶灌木，多刺，果可食，北方荒山阳坡常见。"}},
]
